baseURL: 'https://www.moyeraz.com/'
languageCode: 'en-us'
title: 'Moyer Realty Services'
theme: 'moyer'

pagination:
    pagerSize: 6

markup:
    goldmark:
        renderer:
            unsafe: true
        parser:
            attribute:
                block: true
            wrapStandAloneImageWithinParagraph: false

minify:
    tdewolff:
        html:
            keepWhitespace: false
        js:
            keepVarNames: false
            keepClassNames: false
        css:
            keepCSS2: false
        svg:
            precision: 2

outputFormats:
    json:
        baseName: "index"
        mediaType: "application/json"
        isPlainText: true

menus:
    main:
        - identifier: 'home'
          name: 'Home'
          pageRef: '/'
          weight: 10
        - identifier: 'buyers'
          name: 'Buyers'
          pageRef: '/buyers/'
          weight: 20
        - identifier: 'sellers'
          name: 'Sellers'
          pageRef: '/sellers/'
          weight: 30
        - identifier: 'articles'
          name: 'Articles'
          pageRef: '/articles/'
          weight: 40
        - identifier: 'about'
          name: 'About Us'
          pageRef: '/about-us/'
          weight: 50

outputs:
    home:
        - html
        - rss
        - webappmanifest
        - json  # Structured data (for rich snippets)
    section:
        - html
        - rss
    taxonomy:
        - html
    term:
        - html

permalinks:
  articles: /articles/:slug/

taxonomies:
    category: categories

markup:
  tableOfContents:
    startLevel: 2
    endLevel: 4
    ordered: false


module:
    hugoVersion:
        extended: true
        min: 0.112.0
    mounts:
        - source: assets
          target: assets
        - source: hugo_stats.json
          target: assets/watching/hugo_stats.json

build:
    writeStats: true
    cachebusters:
        - source: assets/watching/hugo_stats\.json
          target: main\.scss
        - source: (postcss|tailwind)\.config\.js
          target: css
        - source: assets/.*\.(js|ts|jsx|tsx)
          target: js
        - source: assets/.*\.(.*)$
          target: $1
    noChmod: true
    noTimes: true

params:
    dateformat: "January 2, 2006"
    sitename: "Moyer Realty Services"
    logo:
        image: "/images/logo_moyer-realty-services.svg"
        width: 440
        height: 150
    image: "/images/social-share.jpg"
    linkedin: "https://www.linkedin.com/company/moyer/"
    youtube: "https://www.youtube.com/@moyeraz"
    description: "Discover premier real estate solutions with Moyer Realty Services. Expert guidance for buying, selling, and investing in properties."
    author: "James Moyer"
    og_image: "/images/social-share.jpg"
    twitter:
        card: "summary_large_image"
        site: "@moyeraz"
    email: "info@moyeraz.com"
    tel: "+1-480-861-4328"
    recaptcha_key: "6Le0yXcqAAAAAODFVOrAptYNEvJ0Ox327pmmsSYh"
    address:
        streetAddress: "N/A"
        locality: "Tucson"
        region: "Arizona"
        code: "85706"
        country: "US"
    founder:
        name: "James Moyer"
        date: "2009"
    working_hours:
        - days: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"]
          opens: "08:30"
          closes: "18:00"
        - days: ["Saturday", "Sunday"]
          opens: "ByAppointment"
          closes: "ByAppointment"
    area_served:
        - "Benson, Arizona"
        - "Green Valley, Arizona"
        - "Marana, Arizona"
        - "Oro Valley, Arizona"
        - "Red Rock, Arizona"
        - "Rio Rico, Arizona"
        - "Saddlebrooke, Arizona"
        - "Sahuarita, Arizona"
        - "Tubac, Arizona"
        - "Tucson, Arizona"
        - "Vail, Arizona"
    price_range: "$100,000 - $30,000,000"
    modals:
        contact-us:
            id: "contact-us-modal"
            title: "Get in Touch with Our Team"
            description: "Have questions about buying or selling? Reach out to us."
        seller:
            id: "seller-modal"
            title: "Get a Free Home Valuation"
            description: "Find out how much your home is worth today."
        buyer:
            id: "buyer-modal"
            title: "Start Your Home Search"
            description: "Let us help you find the perfect home."
    categories:
    Home Buying Guide:
        - First-Time Buyers
        - Mortgage & Financing
        - Finding the Right Home
        - Making an Offer
        - Closing Process

    Home Selling Guide:
        - Pricing & Valuation
        - Preparing Your Home
        - Marketing Your Home
        - Negotiating Offers
        - Closing Process

    Real Estate Market Insights:
        - Local Market Reports
        - Housing Market Forecasts
        - Investment Strategies

    Homeownership & Maintenance:
        - Home Maintenance Tips
        - Renovations & Improvements
        - Energy Efficiency & Sustainability
        - HOA & Community Living

    Moving & Relocation:
        - Moving Tips
        - Best Neighborhoods
        - Relocation Services

    Common Real Estate Questions & FAQs:
        - Legal & Contract Questions
        - Real Estate Terminology
        - Working with an Agent
