baseURL: http://localhost:1313

disableLiveReload: false

buildDrafts: true
buildExpired: true
buildFuture: true

minify:
  minifyOutput: false

params:
  google_analytics: ""  # Prevent analytics tracking
  debug: true  # Enable debug features in templates

outputs:
  home:
    - html
    - json
  articles:
    - html
    - json

server:
  watch: true  # Rebuild site on file changes
  port: 1313  # Default port for development
  gzip: false  # Disable gzip for easier debugging
  cache:
    max_age: 0  # No caching for real-time updates
    immutable: false  # Prevent caching issues in development
  baseURL: http://localhost:1313  # Explicitly set local baseURL

