baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  recaptcha_key: "6Leq8XoqAAAAADMLU5CvrDDrRodR63qswu5l4mcv"
