baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  recaptcha_site_key: "your-default-site-key"  # Set as a placeholder, no environment function here
  recaptcha_secret_key: "your-default-secret-key"  # Placeholder, no environment function here
