baseURL: 'https://www.moyeraz.com'
minify:
  tdewolff:
    html:
      minify: true  
      keepWhitespace: false  
    css:
      minify: true  
    js:
      minify: true  
enableRobotsTXT: true
params:
  recaptcha_key: "6LfurHAqAAAAANhAmqivzCi7eBPRv8mihPHB_qil"  
outputs:
  home:
    - html
    - rss
    - webappmanifest
    - sitemap
