baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  recaptcha_key: "your-default-site-key"  # This will be replaced by Kinsta's environment variable if available
  recaptcha_secret_key: "your-default-secret-key"  # This also will be replaced by Kinsta's environment variable if available
