baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  recaptcha_site_key: "6LfurHAqAAAAANhAmqivzCi7eBPRv8mihPHB_qil"  # Place your actual site key here
