baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  recaptcha_site_key: "6Leq8XoqAAAAADMLU5CvrDDrRodR63qswu5l4mcv"  # Your actual site key
  recaptcha_secret_key: "your-default-secret-key"  # Set a placeholder or leave it as is
