baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  # Leave these keys empty; we'll handle them in templates
  recaptcha_site_key: ""
  recaptcha_secret_key: ""
