baseURL: https://www.moyeraz.com

minify:
  tdewolff:
    html:
      keepWhitespace: false
    css:
      keepComments: false
    js:
      mangle: true
      compress: true

enableRobotsTXT: true
robots:
  disallow:
    - /drafts/
    - /admin/
    - /search/
  allow: /

sitemap:
  changeFreq: "weekly"  # Default change frequency for all items in the sitemap
  priority: 0.5         # Default priority for all items in the sitemap
  exclude:              # Exclude specific sections or types of content
    - drafts
    - admin

params:
  google_analytics: "{{ if eq hugo.Environment `production` }}G-QWQ0H5N569{{ end }}"  # Only enable GA in production
  recaptcha_key: "6LfurHAqAAAAANhAmqivzCi7eBPRv8mihPHB_qil"
  image_processing:
    enable: true
    formats:
      - webp
      - avif
    sizes:
      default: 800
      large: 1200
      small: 400
  og_metadata:
    title: "Moyer Realty Services - Southern Arizona Real Estate Experts"
    description: "Expert guidance for buying, selling, and investing in Southern Arizona properties. Your trusted real estate partner."
    image: "/images/og-social-image.jpg"
  security:
    headers:
      content_security_policy: "default-src 'self'; img-src 'self' data: https://*.moyeraz.com; script-src 'self' https://www.google-analytics.com; style-src 'self' 'unsafe-inline';"
      strict_transport_security: "max-age=31536000; includeSubDomains"
      x_content_type_options: "nosniff"
      x_frame_options: "DENY"

server:
  gzip: true
  brotli: true
  cache:
    max_age: 31536000  # Cache assets for 1 year
    immutable: true    # Use immutable caching for static assets

outputs:
  home:
    - html
    - rss
    - sitemap
    - json
  breadcrumb:
    - json
