baseURL: ''
minify:
  tdewolff:
    html:
      minify: true  # Minify HTML
      keepWhitespace: false  # Removes unnecessary whitespace
    css:
      minify: true  # Minify CSS files
    js:
      minify: true  # Minify JavaScript files
enableRobotsTXT: true

params:
  recaptcha_key: {{ getenv "reCAPTCHA_Site_Key" | default "your-default-site-key" }}
  recaptcha_secret_key: {{ getenv "reCAPTCHA_Secret_Key" | default "your-default-secret-key" }}
